### ISSUE TITLE
Repo Tasks prior to v2.0.0

### ISSUE THREAD

**Issue by jackzampolin** [strangelove-ventures/horcrux#3]
The following are individual tasks that need to be done to get this in proper order for other users to user it:
- [x] Have tests run in CI. https://github.com/strangelove-ventures/horcrux/pull/7
- [x] Additional Tests https://github.com/strangelove-ventures/horcrux/issues/8
- [x] Update readme with install instructions and how to configure https://github.com/strangelove-ventures/horcrux/issues/9
- [x] Update doc on running horcrux https://github.com/strangelove-ventures/horcrux/issues/10
- [x] Refactor signer start into many smaller functions and move logic to the the `signer/` directory https://github.com/strangelove-ventures/horcrux/issues/12
- [x] Improve error and success logging to make operating signer easier https://github.com/strangelove-ventures/horcrux/issues/13
- [x] `--config` flag to `--home` flag https://github.com/strangelove-ventures/horcrux/issues/14
- [x] Automated releases https://github.com/strangelove-ventures/horcrux/issues/15
- [x] Version simd test containers based on sdk version in go.mod and also clean up docker release story https://github.com/strangelove-ventures/horcrux/issues/17
- [x] Document and diagram server interactions
- [x] Add commands to read and modify state files https://github.com/strangelove-ventures/horcrux/issues/18
